name:  Build
#on:
 # workflow_dispatch:
 #   inputs:
 #     logLevel:
 #       description: 'Log level'
 #       required: true
 #       default: 'warning'
 #       type: choice
 #       options:
 #       - info
 #       - warning
 #       - debug
 #     tags:
 #       description: 'Test scenario tags'
 #       required: false
 #       type: boolean
 #     environment:
 #       description: 'Environment to run tests against'
 #       type: environment
 #       required: true

#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build
      - name: Install Snyk CLI
        run: |
          wget https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk-linux
          sudo mv -f snyk-linux /usr/local/bin/
      - name: Run Snyk scan
        timeout-minutes: 5
        run: |
          SNYK_TOKEN=$SNYK_API_TOKEN
          snyk-linux test --all-projects --org=$SNYK_ORG

