name:  Build
#on:
 # workflow_dispatch:
 #   inputs:
 #     logLevel:
 #       description: 'Log level'
 #       required: true
 #       default: 'warning'
 #       type: choice
 #       options:
 #       - info
 #       - warning
 #       - debug
 #     tags:
 #       description: 'Test scenario tags'
 #       required: false
 #       type: boolean
 #     environment:
 #       description: 'Environment to run tests against'
 #       type: environment
 #       required: true

#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build
      - name: Synk installation
        run: curl https://static.snyk.io/cli/latest/snyk-linux -o snyk && \
            chmod +x snyk && \
            sudo mv -f snyk /usr/local/bin/
            
      - name: Synk integration
        run: SNYK_TOKEN=$SNYK_API_TOKEN && \
            snyk test --all-projects --org=$SNYK_ORG