name:  Build
#on:
 # workflow_dispatch:
 #   inputs:
 #     logLevel:
 #       description: 'Log level'
 #       required: true
 #       default: 'warning'
 #       type: choice
 #       options:
 #       - info
 #       - warning
 #       - debug
 #     tags:
 #       description: 'Test scenario tags'
 #       required: false
 #       type: boolean
 #     environment:
 #       description: 'Environment to run tests against'
 #       type: environment
 #       required: true

#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle build
        run: ./gradlew :build
      - name: Synk installation
        run: chmod +x ../snyk/snyk_conf.sh \
        bash ../snyk/snyk_conf.sh 