name:  Build
#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build

  run_sast_scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Install Snyk CLI
        run: |
          wget https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk-linux
          sudo mv -f snyk-linux /usr/local/bin/
          echo "synk package successfully installed..."
      - name: Run Snyk scan
        shell: bash
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
#          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          set -x
          sudo snyk-linux auth 292c9ef6-7c83-408c-b63d-0c608cea0e97
          sudo snyk-linux code test --org=78b2f53f-b8ed-4a42-940f-60f8f8f18274 --project-name=SNE22-INNOPOLIS/javaspringvulny --severity-threshold=high > vuln.log 2>&1
          ls -l vuln.log
          cat vuln.log
      - name: Upload scan output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: vuln.log

  analyze_scan_results_with_GPT-4:
    runs-on: self-hosted
    needs: run_sast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download a sast results
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
      - name: Analyze Results with GPT-4
        uses: riccardolinares/openai-commit@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_TOKEN }}
          openai-prompt: Provide insights on each line contained in the file output-log-file
          model: GPT-4
#        run: |
          # Example: curl -X POST -H "Authorization: Bearer $OPENAI_API_TOKEN" -d '{"data": "output-log-file"}' https://api.openai.com/v1/analyze

