name:  Build
#on:
 # workflow_dispatch:
 #   inputs:
 #     logLevel:
 #       description: 'Log level'
 #       required: true
 #       default: 'warning'
 #       type: choice
 #       options:
 #       - info
 #       - warning
 #       - debug
 #     tags:
 #       description: 'Test scenario tags'
 #       required: false
 #       type: boolean
 #     environment:
 #       description: 'Environment to run tests against'
 #       type: environment
 #       required: true

#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build
      - name: Synk integration
        run: curl https://static.snyk.io/cli/latest/snyk-linux -o snyk && \
            ./bin/chmod +x ./snyk && \
            mv ./snyk /usr/local/bin/ && \
            SNYK_TOKEN=$SNYK_API_TOKEN && \
            snyk test --all-projects --org=78b2f53f-b8ed-4a42-940f-60f8f8f18274