name:  Build

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build

  run_sast_scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Install Snyk CLI
        run: |
          wget https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk-linux
          sudo mv -f snyk-linux /usr/local/bin/
          echo "synk package successfully installed..."
      - name: Run Snyk scan
        shell: bash
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          set -x
          sudo snyk-linux auth SNYK_TOKEN
          sudo touch test.file
          echo "directory is writable.."
          sudo snyk-linux code test --org=SNYK_ORG --project-name=SNE22-INNOPOLIS/javaspringvulny --severity-threshold=high --json-file-output=snyk.json
        continue-on-error: true
      - name: Upload scan output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: snyk.json

  deploy_to_test_env:
    runs-on: [self-hosted, test_env]
    needs: run_sast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Install docker
      #   run: |
      #     sudo chmod +x installdocker.sh 
      #     bash installdocker.sh

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '11'

      # - name: Build with Maven
      #   run: mvn clean package

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: sudo docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/vuln-java-app:${{ github.sha }}

      # - name: Push Docker image to Docker Hub
      #   run: sudo docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vuln-java-app:${{ github.sha }}
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/vuln-java-app:${{ github.sha }}
        run: |
          sudo docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          sudo docker pull $DOCKER_IMAGE
          sudo docker stop vuln-java-app || true
          sudo docker rm vuln-java-app || true
          sudo docker run -d --name vuln-java-app -p 9000:9000 $DOCKER_IMAGE

  run_dast_scan:
    runs-on: [self-hosted, test_env]
    needs: deploy_to_test_env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.PAT_GITHUB }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://localhost:9000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        continue-on-error: true
      # - name: Upload scan output file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: output-log-file
      #     path: snyk.json



  analyze_scan_results_with_GPT-4:
    runs-on: self-hosted
    needs: run_dast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download sast results
        uses: actions/download-artifact@v4
        with:
          name: output-log-file

      - name: Analyze Results with GPT-4
        env:
          SLACK_WEBHOOKS: ${{ secrets.SLACK_WEBHOOKS }}
          OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}
        run: |
          sudo apt-get update && sudo apt-get install -y python3
          python3 genAI_analysis_to_slack.py