name:  Build
#on:
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gradle build
        run: ./gradlew :build
  run_sast_scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Install Snyk CLI
        run: |
          wget https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk-linux
          sudo mv -f snyk-linux /usr/local/bin/
      - name: Run Snyk scan
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
#          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          SNYK_TOKEN=$SNYK_API_TOKEN
          SNYK_ORG=$SNYK_ORG
          snyk-linux auth $SNYK_TOKEN
          snyk-linux test --all-projects --org=$SNYK_ORG >> sast.log
      - name: Upload scan output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: sast.log
  analyze_scan_results_with_GPT-4:
    runs-on: self-hosted
    needs: run_sast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download a sast results
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
      - name: Analyze Results with GPT-4
        uses: riccardolinares/openai-commit@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_TOKEN }}
          openai-prompt: Provide insights on each line contained in the file output-log-file
          model: GPT-4
#        run: |
          # Example: curl -X POST -H "Authorization: Bearer $OPENAI_API_TOKEN" -d '{"data": "output-log-file"}' https://api.openai.com/v1/analyze

